name: Debug schedule

on:
  schedule:
    - cron: '00 22 * * 0-4'

jobs:
  build:
    name: Debug schedule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: echo sha
        run: echo $GITHUB_SHA
